### ISSUE TITLE
分类，回归，交叉验证

### ISSUE THREAD

**Issue by AmosJoseph** [datawhalechina/thorough-pytorch#14]
能不能添加一个回归的例子？

然后分类和回归分别采用交叉验证？

**Comment by NoFish-528** [comment]
收到，尽快更新

**Comment by NoFish-528** [comment]
@AmosJoseph

**Comment by AmosJoseph** [comment]
啥时候更新呢？

**Comment by NoFish-528** [comment]
> 啥时候更新呢？

最近创作的同学都比较忙，如果您已经实现了，我们欢迎您进行pr贡献，谢谢

**Comment by NoFish-528** [comment]
@AmosJoseph 我在一个代码实现中使用了交叉验证 您可以看下[kfold](https://github.com/NoFish-528/Seg/blob/872f7a25138bc04e34d6edf366ec7e3206d82bfb/ours/train.py#L154)
