### ISSUE TITLE
Issue on page /第六章/6.1 自定义损失函数.html

### ISSUE THREAD

**Issue by Key-Kanon** [datawhalechina/thorough-pytorch#16]
![image](https://user-images.githubusercontent.com/35908143/169802259-689655b4-afb2-44e2-8a98-0e58a4910e09.png)

6.1.2 的 def forward(self,inputs,targets,smooth=1) 代码行应该往左边移动，与 def __init__ 对齐

**Comment by NoFish-528** [comment]
已修复
