### ISSUE TITLE
Issue on page /第六章/6.5 数据增强-imgaug.html

### ISSUE THREAD

**Issue by Key-Kanon** [datawhalechina/thorough-pytorch#18]
![image](https://user-images.githubusercontent.com/35908143/169803189-578fdc4d-1ee7-408c-beac-5d36991ec0ce.png)

m 变量在之前未被定义过，应该是 img 才对。

![image](https://user-images.githubusercontent.com/35908143/169803398-829bfc71-77bb-4fd9-9ede-6c64955746cb.png)

同样的，image 变量也未被定义过，应该改为 img。

**Comment by NoFish-528** [comment]
收到，晚一点修改

**Comment by NoFish-528** [comment]
已修改
