### ISSUE TITLE
第二章-2.1张量

### ISSUE THREAD

**Issue by yuanyihan** [datawhalechina/thorough-pytorch#3]
![image](https://user-images.githubusercontent.com/13014170/136936285-985be3e3-d805-4984-a0e1-948e68908d34.png)

1. 空缺
```python
# rand是[0,1)均匀分布 #https://pytorch.org/docs/1.9.1/generated/torch.rand.html#torch.rand
# randn是服从N（0，1）的正态分布 #https://pytorch.org/docs/1.9.1/generated/torch.randn.html#torch.randn
```
2. 参数不足
```python
#normal缺参数， 参考：https://pytorch.org/docs/1.9.1/generated/torch.normal.html#torch.normal
print(torch.normal(4.0,3.0,(4,)))
```
3. 可能是版本问题，我这边是1.9.0，函数找不到
```python
#uniform 找不到
print(torch.__version__)
help(torch.uniform)
```
![image](https://user-images.githubusercontent.com/13014170/136936808-d9b4152c-67ba-400c-809d-918bb6360684.png)

**Comment by LiJiaqi96** [comment]
多谢建议，对应点如下：
1. 已补充  
2. torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))。这种情况是可以的
3. 可能是更新前版本的内容，已删除，与时俱进:)
