### ISSUE TITLE
Issue on page /第三章/3.3 数据读入.html

### ISSUE THREAD

**Issue by guaguagua** [datawhalechina/thorough-pytorch#31]
1. 没有看到对MyDataset的使用呢？
2. 文件的格式能提供一些说明吗，不然和代码对不上，谢谢。

**Comment by NoFish-528** [comment]
您好，您的问题我们已经收到
第一个问题：
关于Mydataset只需要将下面代码的dataset.ImageFolder()改成MyDataset即可
```
import torch
from torchvision import datasets
train_data = datasets.ImageFolder(train_path, transform=data_transform)
val_data = datasets.ImageFolder(val_path, transform=data_transform)
```
第二个问题：
　CIFAR10数据集共有60000张彩色图像，这些图像是32*32，分为10个类，每类6000张图。这里面有50000张用于训练，构成了5个训练批，每一批10000张图；另外10000用于测试，单独构成一批。测试批的数据里，取自10类中的每一类，每一类随机取1000张。在代码中我们也可以看到Image.open()进行数据的读取，跟代码是对的上的。
@guaguagua
