### ISSUE TITLE
第三章 余弦相似度代码

### ISSUE THREAD

**Issue by yinghaodang** [datawhalechina/thorough-pytorch#39]
<img width="313" alt="kk" src="https://user-images.githubusercontent.com/49315320/203687861-df741b96-b01f-4245-a89f-2fba630b2879.png">
我使用的是1.13.0+cu116的pytorch,结果没有错，估计是新版本的问题...
<img width="369" alt="df" src="https://user-images.githubusercontent.com/49315320/203688062-65bceb23-6561-4e7d-bc28-f97864cda061.png">

**Comment by NoFish-528** [comment]
> <img alt="kk" width="313" src="https://user-images.githubusercontent.com/49315320/203687861-df741b96-b01f-4245-a89f-2fba630b2879.png">
> 
> 我使用的是1.13.0+cu116的pytorch,结果没有错，估计是新版本的问题...
> <img alt="df" width="369" src="https://user-images.githubusercontent.com/49315320/203688062-65bceb23-6561-4e7d-bc28-f97864cda061.png">

与代码版本无关，代码中target的设置出现问题，更改为下方代码即可：
```python
loss_f = nn.CosineEmbeddingLoss()
inputs_1 = torch.tensor([[0.3, 0.5, 0.7], [0.3, 0.5, 0.7]])
inputs_2 = torch.tensor([[0.1, 0.3, 0.5], [0.1, 0.3, 0.5]])
target = torch.tensor([1, -1], dtype=torch.float)
output = loss_f(inputs_1,inputs_2,target)
```
