### ISSUE TITLE
第七章 7.2.3部分 一个变量未被定义

### ISSUE THREAD

**Issue by yinghaodang** [datawhalechina/thorough-pytorch#42]
<img width="960" alt="7 2 3" src="https://user-images.githubusercontent.com/49315320/204078869-a32ab88d-4dc0-4f7e-bfe2-73921cf665d1.png">
我自己的一个修改方法：
将img_tensor 改为
torch.tensor(rgb_img).permute(2,0,1).unsqueeze_(0)
rgb_img在前文被定义，shape为224, 224, 3 的ndarray

**Comment by NoFish-528** [comment]
img_tensor 是一个用户自定义的图片张量
