### ISSUE TITLE
3.3数据读入，class MyDataset(dataset)26行

### ISSUE THREAD

**Issue by LiHui1116** [datawhalechina/thorough-pytorch#47]
3.3数据读入，class MyDataset()这段代码26行发现了一个错误：raw_label = self.label_info.loc[self.label_info['Image_index'] == image_name]，这里self.label_info['Image_index'] == image_name是一个关系式，其结果为布尔值，self.label_info.loc[1]或者self.label_info.loc[0]无法取值，这里是不是应该改为` if self.label_info['Image_index'] == image_name：    
 raw_label = self.label_info.loc[self.label_info['Image_index'] ]`

**Comment by NoFish-528** [comment]
@LiHui1116 非常荣幸收到您提出的issue，我们更换了MyDataset的定义方式，以一种更加简洁的方式进行介绍。具体的实战应用可以参考notebook里面的Dataset的定义

**Comment by NoFish-528** [comment]
https://github.com/datawhalechina/thorough-pytorch/blob/main/source/%E7%AC%AC%E4%B8%89%E7%AB%A0/3.3%20%E6%95%B0%E6%8D%AE%E8%AF%BB%E5%85%A5.md
