### ISSUE TITLE
[求助][盼复]：Windows 10 cuda 11.6 没能正常安装torch，\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by itknight** [datawhalechina/thorough-pytorch#48]
### 系统环境
![image](https://user-images.githubusercontent.com/7972442/209610452-a05617ae-7468-45e7-a82f-aff5dc291228.png)

### 安装过程
![image](https://user-images.githubusercontent.com/7972442/209610191-fbafacee-5b8d-49de-b8aa-e22bf5ff8372.png)

### 如图出现了问题
![image](https://user-images.githubusercontent.com/7972442/209610639-52699b87-3247-400f-80c9-8eacdecc59d5.png)

通过网络百度了，让安装 vc_redist 没有解决
![image](https://user-images.githubusercontent.com/7972442/209610711-4bcfa0e3-cc08-468d-94f3-7206e16adec9.png)

![image](https://user-images.githubusercontent.com/7972442/209611863-91078124-1bd3-4e45-9681-f18dc9896e4d.png)

已没招，盼复~

**Comment by itknight** [comment]
去注册论坛，没有收到激活邮件，

**Comment by NoFish-528** [comment]
@itknight 你的问题我已经收到，我有以下建议希望能帮助到你
1. 官方提供了cuda11.6的安装命令，如下
```python
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
```
2. 我在StackOverflow发现有一些是因为没有安装cudatoolkit引起的，可以使用conda安装
3. 官方forum同类问题：[url](https://discuss.pytorch.org/t/paging-file-problems-when-trying-to-import-torch/160373)
4. stackoverflow有人建议重现建一个新的虚拟环境重新再来一次
