### ISSUE TITLE
自动求导学习提出建议

### ISSUE THREAD

**Issue by YanjiNing** [datawhalechina/thorough-pytorch#5]
1.pytorch内部雅可比向量积是如何计算的，是否可以给出数学公式
2.
![image](https://user-images.githubusercontent.com/20925529/140247099-80640452-6fc0-47b2-a281-a5e6a52380ee.png)

.grad_fn是对tensor计算一次就引用一次Function对象，来产生运算结果，记录运算的发生，保存记录运算的输入，tensor使用.grad.fn属性记录这个计算图的入口，反向传播中，autograd引擎会按照逆序，通过function的backward依次计算梯度. 
手动创建这里建议给出例子,比如:
![image](https://user-images.githubusercontent.com/20925529/140247126-22b175ce-ac85-42d6-8bd3-baacec015373.png)
3.对于markdown公式无法显示问题，是否能改善一下，阅读体验不佳
4.
![image](https://user-images.githubusercontent.com/20925529/140247426-9dcb3d61-ac47-4777-a450-d0de2b02ed65.png)
对于开篇的这些总结，感觉可以在下面对应代码块的头部进行匹配，这样对于小白来说阅读起来会更容易理解一些，不会摸不着头脑，可以适当在结尾处对知识点做一些总结。

**Comment by LiJiaqi96** [comment]
非常感谢上述建议！
1. 这个我们去找一下pytorch的实现方式，尽量满足用户的需求。另外，pytorch课程可能更多的是介绍原理方面的内容，这里打个广告，如果对背后的原理感兴趣可以参与课程成员刘洋的[深度学习理论课](https://github.com/datawhalechina/unusual-deep-learning)  。
2. 已添加说明。  
3. 建议使用Chrome浏览器，同时安装对应公式插件MathJax Plugin for Github。大部分情况下均可解决，如果还有问题欢迎反馈。另外可能是由于网络问题导致的公式加载不畅，可以考虑参考项目的[Gitee](https://gitee.com/datawhalechina/thorough-pytorch)。  
4. 这个建议很好，我们会系统梳理一下，然后更新文档，非常感谢！
