### ISSUE TITLE
9.1模型部署pipeline框架图无法正常显示

### ISSUE THREAD

**Issue by LiHui1116** [datawhalechina/thorough-pytorch#51]
我看了下源码，可能是图片添加错误，或者图片丢失。单独放浏览器渲染不出来，麻烦更新一下框架图。辛苦作者！

**Comment by NoFish-528** [comment]
@LiHui1116 可以尝试看下source/第九章里面看markdown原文档，我这里显示是没有问题的 : )

**Comment by LiHui1116** [comment]
谢谢提醒！
