### ISSUE TITLE
Issue on page /第九章/9.1 使用ONNX进行部署并推理.html

### ISSUE THREAD

**Issue by leeqiaogithub** [datawhalechina/thorough-pytorch#55]
When converting a quantization model from pytorch to onnx, I found that there was a large error (more than 4%) in the inference accuracy between the two models. I want to know is that reasonable? And how to solve it? Looking forward to your reply

**Comment by NoFish-528** [comment]
first of all, I'm not particularly good at quantization and deployment, but I guess there could be several reasons
1. I don't know what model are you use, maybe there are some operator isn't good support
2. There may be slight differences in how PyTorch and ONNX handle numerical computations, which can accumulate and result in accuracy drops, especially for quantized models.
3. I think you can check layer by layer accuracy between PyTorch and ONNX to detect where the discrepancies are coming from
4. I'm not sure that the acc will decline when you export an onnx model from a quantization model, my best suggestion is to export the onnx model from none quantizeation mode.

Good luck to you, if you think this repo is helpful you, please star and publicize. @leeqiaogithub
