### ISSUE TITLE
这里是不是写错了？

### ISSUE THREAD

**Issue by Arthurrrrking** [datawhalechina/thorough-pytorch#62]
![image](https://github.com/datawhalechina/thorough-pytorch/assets/137430307/e9b8e040-8310-467c-ab67-a66a0450e234)
FN是否应为实际为阳性，模型检测为阳性
TN是否应为实际为阴性，模型检测为阳性

**Comment by NoFish-528** [comment]
> ![image](https://github.com/datawhalechina/thorough-pytorch/assets/137430307/e9b8e040-8310-467c-ab67-a66a0450e234)
> FN是否应为实际为阳性，模型检测为阳性
> TN是否应为实际为阴性，模型检测为阳性

thx，T/F 对应的是预测结果是实际结果是否相同，N/P对应是负样本还是正样本。

真实值是positive，模型认为是positive的数量（True Positive=TP）
真实值是positive，模型认为是negative的数量（False Negative=FN）：这就是统计学上的第一类错误（Type I Error）
真实值是negative，模型认为是positive的数量（False Positive=FP）：这就是统计学上的第二类错误（Type II Error）
真实值是negative，模型认为是negative的数量（True Negative=TN）

**Comment by NoFish-528** [comment]
@Arthurrrrking

**Comment by Arthurrrrking** [comment]
@NoFish-528 好的，我理解有误，感谢
