### ISSUE TITLE
Issue on page /第五章/5.4 PyTorh模型保存与读取.html

### ISSUE THREAD

**Issue by LYCnight** [datawhalechina/thorough-pytorch#67]
# 这一节有一些代码错误了，附上我修改的代码：
## 1
![image](https://github.com/datawhalechina/thorough-pytorch/assets/100512483/bbff829a-5ff6-490f-8516-a7e975d5c6cd)

改为：
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2'   #这里替换成希望使用的GPU编号
import torch
from torchvision import models

model = models.resnet152(pretrained=True)
model = nn.DataParallel(model).cuda()

保存+读取模型权重
torch.save(model.module.state_dict(), save_dir)

os.environ['CUDA_VISIBLE_DEVICES'] = '0'   #这里替换成希望使用的GPU编号
loaded_model = models.resnet152()   #注意这里需要对模型结构有定义
loaded_model.load_state_dict(torch.load(save_dir))
loaded_model = nn.DataParallel(loaded_model).cuda()
loaded_model.state_dict
```

## 2 
![image](https://github.com/datawhalechina/thorough-pytorch/assets/100512483/e1cc93f7-9cca-4907-986d-774c7d8009fd)

改为：
```
import os
import torch
from torchvision import models
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2'   #这里替换成希望使用的GPU编号
print(os.environ['CUDA_VISIBLE_DEVICES'])

model = models.resnet152(pretrained=True)
model = nn.DataParallel(model).cuda()

# 保存+读取模型权重，强烈建议！！
torch.save(model.module.state_dict(), save_dir)
loaded_model = models.resnet152()   #注意这里需要对模型结构有定义
loaded_model.load_state_dict(torch.load(save_dir))
loaded_model = nn.DataParallel(loaded_model).cuda()
loaded_model
```

## 3
![image](https://github.com/datawhalechina/thorough-pytorch/assets/100512483/4c57af8e-a70f-423b-905a-90168c692940)

请问这里是怎么看的？
希望作者大大解答

```
测试环境：
Ubuntu 22.04
NVIDIA 1080 ti * 4
```

**Comment by NoFish-528** [comment]
> # 这一节有一些代码错误了，附上我修改的代码：
> ## 1
> ![image](https://user-images.githubusercontent.com/100512483/277099215-bbff829a-5ff6-490f-8516-a7e975d5c6cd.png)
> 
> 改为：
> 
> ```
> import os
> os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2'   #这里替换成希望使用的GPU编号
> import torch
> from torchvision import models
> 
> model = models.resnet152(pretrained=True)
> model = nn.DataParallel(model).cuda()
> 
> 保存+读取模型权重
> torch.save(model.module.state_dict(), save_dir)
> 
> os.environ['CUDA_VISIBLE_DEVICES'] = '0'   #这里替换成希望使用的GPU编号
> loaded_model = models.resnet152()   #注意这里需要对模型结构有定义
> loaded_model.load_state_dict(torch.load(save_dir))
> loaded_model = nn.DataParallel(loaded_model).cuda()
> loaded_model.state_dict
> ```
> 
> ## 2
> ![image](https://user-images.githubusercontent.com/100512483/277099281-e1cc93f7-9cca-4907-986d-774c7d8009fd.png)
> 
> 改为：
> 
> ```
> import os
> import torch
> from torchvision import models
> os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2'   #这里替换成希望使用的GPU编号
> print(os.environ['CUDA_VISIBLE_DEVICES'])
> 
> model = models.resnet152(pretrained=True)
> model = nn.DataParallel(model).cuda()
> 
> # 保存+读取模型权重，强烈建议！！
> torch.save(model.module.state_dict(), save_dir)
> loaded_model = models.resnet152()   #注意这里需要对模型结构有定义
> loaded_model.load_state_dict(torch.load(save_dir))
> loaded_model = nn.DataParallel(loaded_model).cuda()
> loaded_model
> ```
> 
> ## 3
> ![image](https://user-images.githubusercontent.com/100512483/277099325-4c57af8e-a70f-423b-905a-90168c692940.png)
> 
> 请问这里是怎么看的？ 希望作者大大解答
> 
> ```
> 测试环境：
> Ubuntu 22.04
> NVIDIA 1080 ti * 4
> ```

感谢你的建议，但是一般情况下我们的权重都是保存成单卡的形式，而不是多卡加module的形式，这样具有更强的通用性。关于问题三，你可以使用
```python
import torch  
import torchvision  
  
# 加载预训练的 ResNet-18 模型  
model = torchvision.models.resnet18(pretrained=True)  
  
# 遍历模型的每一层并打印层名称  
for name, layer in model.named_children():  
    print(f"layer: {name}")  
```

**Comment by NoFish-528** [comment]
@LYCnight
