### ISSUE TITLE
图片

### ISSUE THREAD

**Issue by airainday** [datawhalechina/thorough-pytorch#70]
文档图片都挂了怎么解决啊

**Comment by NoFish-528** [comment]
> 文档图片都挂了怎么解决啊

请具体指出哪一个章节？方便我查看问题

**Comment by WenkeRen** [comment]
遇到类似问题，例如第零章的模型评价指标中的第一张图片，网页原代码中指向为
`<img src="[figures/normalized_confusion_matrix.png](https://datawhalechina.github.io/thorough-pytorch/%E7%AC%AC%E9%9B%B6%E7%AB%A0/figures/normalized_confusion_matrix.png)" align="center" style="zoom:50%;" />`
但是这个链接地址实际上是404的，那一章其他图片也是同样的问题，烦请检查一下。

**Comment by shenweiyan** [comment]
> 遇到类似问题，例如第零章的模型评价指标中的第一张图片，网页原代码中指向为 `<img src="[figures/normalized_confusion_matrix.png](https://datawhalechina.github.io/thorough-pytorch/%E7%AC%AC%E9%9B%B6%E7%AB%A0/figures/normalized_confusion_matrix.png)" align="center" style="zoom:50%;" />` 但是这个链接地址实际上是404的，那一章其他图片也是同样的问题，烦请检查一下。

我也发现到这个问题了~
![image](https://github.com/datawhalechina/thorough-pytorch/assets/26101369/fe999d84-931f-4c10-b55d-7f9900e31f43)

**Comment by lifeformg** [comment]
+1

**Comment by Sun0308** [comment]
+1

**Comment by edc3000** [comment]
+1

**Comment by ZhikangNiu** [comment]
最好查看原始markdown文档

**Comment by cjqshu** [comment]
> +1，图片最好能够显示正常，方便后来者查看

问题原因：docs中的章节却少所对应的figure文件夹。
解决方案：将source文件夹下各章节的figures复制到docs里所对应的章节目录下，网页版就能正常显示图片。

**Comment by cjqshu** [comment]
> 最好查看原始markdown文档

希望作者能将修复一下网页版的部分图片缺失问题，应该就是docs的各章节缺少对应的figures文件夹所导致的。
