### ISSUE TITLE
CH1 12.2.3 PyTorch的离线安装

### ISSUE THREAD

**Issue by SunXiaoXiang** [datawhalechina/thorough-pytorch#73]
step 5:离线下载
问题描述：下载pytorch、torchvision压缩包后，使用conda install --offline安装，安装完成后，无法在python中import torcch
其他验证：采用在线安装后，可以import torch
环境说明：macOS v12.3.1 python 3.8 conda 23.1.0

**Comment by laffycat** [comment]
有关PyTorch的离线安装可以参照下列内容：

**Comment by NoFish-528** [comment]
This problem is solved in #78

**Comment by NoFish-528** [comment]
@SunXiaoXiang
