### ISSUE TITLE
可能需要notebook文件直接运行代码

### ISSUE THREAD

**Issue by moon4869** [datawhalechina/thorough-pytorch#9]
从第三章开始后面感觉基本上都需要运行代码来查看对应的结果，但是目前主要提供的是markdown的文件，可能出于让学员手动敲命令加强学习效果的意图，所以没有提供jupyter notebook格式的文件？
我暂时采取的方案是使用notedown将markdown文件直接转为notebook文件来运行，效果还可以，但是需要手动去转换。所以想问下有没有直接提供notebook文件的计划？非常感谢

**Comment by Relph1119** [comment]
感觉提供notebook效果并不是很好，可以自己使用notebook写笔记，可以参考我的Github：https://github.com/Relph1119/my-team-learning/tree/master/notebook/pytorch_learning35/my_homework

**Comment by LiJiaqi96** [comment]
每章内容基本都会有对应的直播讲解，直播后notebook会放到github上。另外也建议参考 @Relph1119 的做法。

**Comment by moon4869** [comment]
好的好的，感谢
